version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3101:3000"  # Map host port 3101 to container port 3000
    environment:
      - NODE_ENV=production
    restart: always  # Automatically restart the container on failure
